### ISSUE TITLE
Management + function command that cleans expired invites

### ISSUE THREAD

**Issue by caspervdw** [nens/nens-auth-client#31]
See #25

- management command that cleans invites older than X days
- call a function that cleans invites older than X days

**Comment by lexvand** [comment]
@caspervdw
Configured the task as test on staging. Running it fails with error:
`Traceback (most recent call last):
  File "/srv/nxt3.staging.lizard.net/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied for table nens_auth_client_invitation`

**Comment by caspervdw** [comment]
@byrman This is a database permission issue. The taskserver has insufficient privilege on the (newly created) table ``nens_auth_client_invitation``.

Migrations are run from webservers. Is that wrong? Maybe the roles are different on staging than on production?

related: https://github.com/nens/lizard-nxt/pull/4590

**Comment by byrman** [comment]
> Migrations are run from webservers. Is that wrong?

Yes, apart from the permission problems that's dangerous, because the webservers have a statement timeout configured. Long running (data) migrations might fail. I'll will address both issues in a fix.
