### ISSUE TITLE
Only accept invitations if invitation email matches users email

### ISSUE THREAD

**Issue by caspervdw** [nens/nens-auth-client#43]
Currently, anyone with an invitation link can accept the invitation link. So if I send an invitation to pietje@company.nl , pietje can log in using his personal Google account (like pietje@gmail.com) and have the permissions given to pietje@utrecht.nl associated with his personal account. After pietje is fired at company.nl, he will still be able to authenticate and use its permissions previously given to pietje@utrecht.nl

This might be desirable. For instance, I might want to log in everywhere with my personal account. But from the security point of view, I think it is undesirable. The current design makes the "invitation link" a secret that enables access to lizard without any further security measure. So if you steal the invitation link, you can directly acquire the permissions associated with that link.

If the invitation would only be usable by the owner of the email (like pietje@company.nl), then pietje would be required to use his company account, which will automatically be void after he is fired at the company.  Also, the invitation link becomes much less interesting for attackers - an attacker would still need to be able to authenticate as pietje@company.nl 

What do you think @reinout @joeriverheijden  ? It is an easy check to implement but with significant consequences.

**Comment by reinout** [comment]
Better to add a check.

Note: I wouldn't pay attention to whether the emailadress passed to us has "verified=True" set on it, as that might make everything harder to get to work.

**Comment by lexvand** [comment]
Can't be tested due to Pre-signup timeout. See nens/tf-cognito#56
