### ISSUE TITLE
Logout problem after PermissionDenied

### ISSUE THREAD

**Issue by caspervdw** [nens/nens-auth-client#48]
Say I try to log in into lizard with my personal google account, without having received an invitation. Then I get a PermissionDenied error.

The problem is that if I try to login again, I am still logged in on AWS Cognito, so that I get the same PermissionDenied error. There is no way to logout (if you call /logout, it doesnt do anything because you are logged out locally).

Having two endpoints seems to be a way to solve this:

- /logout  logs out locally and redirects to AWS Cognito with "logout_url=localhost/logout_success/"
- /logout_success  just redirects to whatever the user specified as next url in the first place

This requires a change in the AWS config as well.

@reinout  What do you think of this one?

**Comment by reinout** [comment]
Well, you first have to *know* that you have to try to log out somehow.

Perhaps a link on the actual error page that returns you to cognito and logs you out, there? Ideally it then redirects to a login page again. Or perhaps there's even a re-login option you can pass to cognito?
"You might have selected a wrong account to log in with. If so, _logout_ and try again".

**Comment by caspervdw** [comment]
Yes that is also true. So 1) you cannot logout and 2) users do not know how to logout.

We can separate the two views and then add a logout link to the 403 error?

**Comment by lexvand** [comment]
Works nicely.
