### ISSUE TITLE
Better username creation on create_user

### ISSUE THREAD

**Issue by caspervdw** [nens/nens-auth-client#49]
Currently, create_user just takes the "cognito:user" claim as username. It is not necessary to have app-usernames equal "cognito:user" usernames. It may even give issues:

- Incomprehensible end-user errors if usernames already exist
- Usernames like "google_5123987983659132879" appearing in the top right corner of the front end

I think we can have some better logic here to have nicely formatted usernames that are always unique.

**Comment by lexvand** [comment]
@caspervdw How can this be tested?

**Comment by caspervdw** [comment]
There are two things here:

## New users should get a readable username

Test this by sending an invite to some gmail address. When accepting the invite, a new user in lizard should be created with as username not "google_512312512512423" but something more comprehensible (the email address)

## Existing usernames should not give an error
Remove the RemoteUser associated with the above created. Then send an invitation again. After accepting, a new user should be created and the username should not clash with the existing one. This is done by appending 4 random characters to the username.

**Comment by lexvand** [comment]
Works. For the second use case I suppose it is not a problem that there are two users with the same email address. I guess login always goes through the remote user.
